### ISSUE TITLE
Typo in webhook_config.php

### ISSUE THREAD

**Issue by iankrigsman** [its-tas/stripe-php-webhook#3]
The email settings in webhook_config.php have a typo on the password declaration...

```
  /*
   * SMTP settings
   */
  'use_smtp' => 0,
  'smtp_host' => '',
  'smtp_port' => '',
  'smtp_user' => '',
  'smpt_pass' => '',  // <<< smtp_pass ...
```
Code in webhookclass.php is correct (circa line 552)...

```
                $mail->Username = $this->config['email']['smtp_user'];
                $mail->Password = $this->config['email']['smtp_pass'];
```
I was getting authentication errors and stared at this for ages before discovering the problem !!!

--
Ian

**Comment by jamminjames** [comment]
Yes, me too, thanks! Please correct this, author!

**Comment by jake-yeg** [comment]
Fixed, thanks.
