### ISSUE TITLE
Getting 500 error on tests

### ISSUE THREAD

**Issue by jamminjames** [its-tas/stripe-php-webhook#4]
I think I have it set up correctly, both on our server and on Stripe, but I keep getting a 500 error.

I've tried both the 'whsec' secret and the 'sk_test' secret on the webhook_config.php page. I also corrected the typo mentioned in the other comment. 

What can I do to correct this error? Thanks for any help.

**Comment by jamminjames** [comment]
Okay, I had the 'stripe_path' set up wrong. Now I'm getting a 400 error, but I believe that's because I'm running the test, and it's using a non-existent account number.

However, I'm not getting any log entries in my db, which I believe is set up correctly, as is the logging into the db in webhook_config.php. After running a test webhook on Stripe, shouldn't it log it?

**Comment by jake-yeg** [comment]
Test webhooks send dummy event ID's, which won't work with the event verification method(can't call back to Stripe with an invalid event ID). Not really any way around this, as far as I know.
